import unittest
from src.bb84 import BB84

class TestBB84(unittest.TestCase):

    def setUp(self):
        self.bb84 = BB84(photon_count=10)
        self.bb84.generate_key()
    
    def test_key_length(self):
        """Test that the keys generated by Alice and Bob have the same length."""
        alice_key, bob_key = self.bb84.get_reconciled_key()
        self.assertEqual(len(alice_key), len(bob_key))

    def test_generated_keys(self):
        """Test that the keys generated are not empty."""
        alice_key, bob_key = self.bb84.get_reconciled_key()
        self.assertGreater(len(alice_key), 0)
        self.assertGreater(len(bob_key), 0)

if __name__ == "__main__":
    unittest.main()
