import sys
import os
import unittest

# Add the src directory to the Python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))

from bb84 import BB84  # Import BB84 after adding src to the path

class TestBB84(unittest.TestCase):

    def setUp(self):
        self.bb84 = BB84(photon_count=10)
        self.bb84.generate_key()
    
    def test_key_length(self):
        """Test that the keys generated by Alice and Bob have the same length."""
        alice_key, bob_key = self.bb84.get_reconciled_key()
        self.assertEqual(len(alice_key), len(bob_key))

    def test_generated_keys(self):
        """Test that the keys generated are not empty."""
        alice_key, bob_key = self.bb84.get_reconciled_key()
        self.assertGreater(len(alice_key), 0)
        self.assertGreater(len(bob_key), 0)

if __name__ == "__main__":
    unittest.main()
